-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Pomo.Object.Pomodoro exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Pomo.InputObject
import Pomo.Interface
import Pomo.Object
import Pomo.Scalar
import Pomo.ScalarCodecs
import Pomo.Union


id : SelectionSet Int Pomo.Object.Pomodoro
id =
    Object.selectionForField "Int" "id" [] Decode.int


duration : SelectionSet Int Pomo.Object.Pomodoro
duration =
    Object.selectionForField "Int" "duration" [] Decode.int


start : SelectionSet Int Pomo.Object.Pomodoro
start =
    Object.selectionForField "Int" "start" [] Decode.int


test : SelectionSet Bool Pomo.Object.Pomodoro
test =
    Object.selectionForField "Bool" "test" [] Decode.bool
