-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Pomo.Object.Project exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Pomo.InputObject
import Pomo.Interface
import Pomo.Object
import Pomo.Scalar
import Pomo.ScalarCodecs
import Pomo.Union


id : SelectionSet Int Pomo.Object.Project
id =
    Object.selectionForField "Int" "id" [] Decode.int


name : SelectionSet String Pomo.Object.Project
name =
    Object.selectionForField "String" "name" [] Decode.string


total_duration : SelectionSet Int Pomo.Object.Project
total_duration =
    Object.selectionForField "Int" "total_duration" [] Decode.int


n_pomodoros : SelectionSet Int Pomo.Object.Project
n_pomodoros =
    Object.selectionForField "Int" "n_pomodoros" [] Decode.int


pomodoros :
    SelectionSet decodesTo Pomo.Object.Pomodoro
    -> SelectionSet (List decodesTo) Pomo.Object.Project
pomodoros object____ =
    Object.selectionForCompositeField "pomodoros" [] object____ (Basics.identity >> Decode.list)


as_of : SelectionSet String Pomo.Object.Project
as_of =
    Object.selectionForField "String" "as_of" [] Decode.string


last_touched : SelectionSet Int Pomo.Object.Project
last_touched =
    Object.selectionForField "Int" "last_touched" [] Decode.int
