-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Pomo.Mutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import Pomo.InputObject
import Pomo.Interface
import Pomo.Object
import Pomo.Scalar
import Pomo.ScalarCodecs
import Pomo.Union


type alias PomodoroOptionalArguments =
    { test : OptionalArgument Bool
    , start : OptionalArgument Int
    }


type alias PomodoroRequiredArguments =
    { duration : Int
    , project : String
    }


pomodoro :
    (PomodoroOptionalArguments -> PomodoroOptionalArguments)
    -> PomodoroRequiredArguments
    -> SelectionSet decodesTo Pomo.Object.Pomodoro
    -> SelectionSet decodesTo RootMutation
pomodoro fillInOptionals____ requiredArgs____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { test = Absent, start = Absent }

        optionalArgs____ =
            [ Argument.optional "test" filledInOptionals____.test Encode.bool, Argument.optional "start" filledInOptionals____.start Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "pomodoro" (optionalArgs____ ++ [ Argument.required "duration" requiredArgs____.duration Encode.int, Argument.required "project" requiredArgs____.project Encode.string ]) object____ Basics.identity
