-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Pomo.Object exposing (..)


type Health
    = Health


type Pomodoro
    = Pomodoro


type Project
    = Project
